name: absensi_kegiatan
version: 1.0.0+1
publish_to: none
description: Multiplatform Apps for Absensi Kegiatan
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_svg: ^1.1.6
  intl: ^0.17.0
  syncfusion_flutter_signaturepad: ^20.3.60
  fluttertoast: ^8.1.1
  substring_highlight: ^1.0.33
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/