name: absensi_kegiatan
version: 1.0.2+3
publish_to: none
description: Multiplatform Apps for Presensi Kegiatan by Diskominfo Jateng
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  intl: ^0.17.0
  syncfusion_flutter_signaturepad: ^20.3.60
  substring_highlight: ^1.0.33
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  qr_flutter: ^4.0.0
  path_provider: ^2.0.11
  pretty_qr_code: ^2.0.2
  url_launcher: ^6.1.7
  qr_code_scanner: ^1.0.1
  google_fonts: ^3.0.1
  flutter_markdown: ^0.6.14

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.0
  build_runner: ^1.11.5

flutter:
  uses-material-design: true

  assets:
    - assets/
